# Generated by Django 2.1.7 on 2019-03-19 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acta',
            fields=[
                ('idA', models.AutoField(primary_key=True, serialize=False)),
                ('Actividad', models.CharField(default='Curriculo', max_length=50)),
                ('Fecha', models.DateField(default=datetime.datetime.now)),
                ('Lugar', models.CharField(max_length=50)),
                ('Asistentes', models.TextField(max_length=200)),
                ('Temas', models.TextField(max_length=200)),
                ('Conclusiones', models.TextField()),
            ],
        ),
    ]
