# Generated by Django 2.1.7 on 2019-03-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='Asistentes',
            field=models.TextField(help_text='Cada asistente en una línea', max_length=200),
        ),
        migrations.AlterField(
            model_name='acta',
            name='Conclusiones',
            field=models.TextField(help_text='Cada conclusión en una línea'),
        ),
        migrations.AlterField(
            model_name='acta',
            name='Temas',
            field=models.TextField(help_text='Cada tema en una línea', max_length=200),
        ),
    ]
