# Generated by Django 2.1.7 on 2019-03-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20190319_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='Temas',
            field=models.TextField(help_text='Cada tema en una línea separada'),
        ),
    ]
